### ISSUE TITLE
type '_CompactIterable<OverlayEntry>' is not a subtype of type 'List<OverlayEntry>'

### ISSUE THREAD

**Issue by advancedtw** [rive-app/portal#1]
Tried running the example app and it works until I hot reload and this exception is being thrown.
Could be due to my version of flutter i'm testing against master version 1.14.7-pre.98. Also it's a macos desktop app but looking at the code it shouldn't make a difference.

> Launching lib/main.dart on macOS in debug mode...
> flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> flutter: The following assertion was thrown building MyApp:
> flutter: type '_CompactIterable<OverlayEntry>' is not a subtype of type 'List<OverlayEntry>'
> flutter:
> flutter: The relevant error-causing widget was:
> [38;5;248mflutter:   MyApp[39;49m
> flutter:
> flutter: When the exception was thrown, this was the stack:
> [38;5;248mflutter: #0      PortalProvider.entries[39;49m
> [38;5;248mflutter: #1      PortalProvider.updateShouldNotify[39;49m
> [38;5;244mflutter: #2      InheritedElement.updated[39;49m
> [38;5;244mflutter: #3      ProxyElement.update[39;49m
> [38;5;244mflutter: #4      Element.updateChild[39;49m
> [38;5;244mflutter: #5      ComponentElement.performRebuild[39;49m
> [38;5;244mflutter: #6      Element.rebuild[39;49m
> [38;5;244mflutter: #7      BuildOwner.buildScope[39;49m
> [38;5;244mflutter: #8      WidgetsBinding.drawFrame[39;49m
> [38;5;244mflutter: #9      RendererBinding._handlePersistentFrameCallback[39;49m
> [38;5;244mflutter: #10     SchedulerBinding._invokeFrameCallback[39;49m
> [38;5;244mflutter: #11     SchedulerBinding.handleDrawFrame[39;49m
> [38;5;244mflutter: #12     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>[39;49m
> flutter: (elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
> flutter:
> flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
> Reloaded 1 of 486 libraries in 383ms.

**Comment by rodydavis** [comment]
Fixed with #2
